apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: chinmaykulkarni/networking:frontend
        ports:
        - containerPort: 3001
---
kind: Service
apiVersion: v1
metadata:
  name: fontend-service
spec:
  type: NodePort
  selector:
    app: frontend

  ports:
    - nodePort: 30163
      port: 3001
      targetPort: 3001
